#state and input costs
q_x : 5.0
q_y : 5.0
q_yaw : 1.0
r_v : 2.0
r_steer: 2.0

#state size and input size
nx: 3
nu: 2

#Time Horizon and time-difference for each step
N: 20
Ts: 0.04

#input limits
max_speed: 12.00
max_steer: 0.41

#acceleration limits
ACCELERATION_MAX: 15.0
DECELERATION_MAX: 30.0

C_l: 0.35


