# Config file for planner

# Constants for tuning
lookahead_distance: 1.8

bubble_radius: 0.40

gap_threshold: 2.0
gap_size_threshold: 30

inflation_radius: 3
gap_bubble: 1.0

max_scan: 5.0

folder_path: "/home/mihir/mihir_ws/src/f110_ros/f110_finalProject"
delimiter: ","

collision_points: 100

alpha: 0.8
ref_alpha: 0.02
max_acc: 9.51

# Subscriber topics
scan_topic: "/scan"
ego_odom: "/odom"
opp_odom: "/opp_odom"
dubins_path: "/path_points"
map: "/map"

# Publisher topics
drive_topic: "/drive"
waypoints: "/waypoint_markers"
costmap: "/costmap"
endpoints: "/waypoint"
mpc: "/mpc"
dubins: "/dubins"
constraints: "/constraints"
inputs: "/mpc_inputs"

# TF Frames
map_frame: "map"
ego_car: "ego_racecar/base_link"
opp_car: "opp_racecar/base_link"
ego_laser: "ego_racecar/laser"
left_rear_wheel: "ego_racecar/back_left_wheel"
right_rear_wheel: "ego_racecar/back_right_wheel"
